### ISSUE TITLE
Events not sends on android

### ISSUE THREAD

**Issue by ikuprin** [distriqt/ANE-Firebase#147]
Hi,

I have problem with Events on Android. It's very similar to this issue https://github.com/distriqt/ANE-Firebase/issues/118

I check all configurations - all right. Logcat says me that all identifiers right. But FA not send event.

I'v tried another ane for firebase - all works. Then I'd compare Value.xml in anes - similar. Then I'd compare logcat and saw:

05-04 18:27:03.085 V/FA      (30576): Registered activity lifecycle callback
05-04 18:27:03.128 V/FA      (30576): onActivityCreated
05-04 18:27:03.177 V/FA      (30576): Collection enabled
05-04 18:27:03.178 V/FA      (30576): App package, google app id: air.com.xxx.xxx, 1:xxx:android:xxx
05-04 18:27:03.180 I/FA      (30576): App measurement is starting up, version: 11910
05-04 18:27:03.180 I/FA      (30576): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
05-04 18:27:03.180 I/FA      (30576): To enable faster debug mode event logging run:
05-04 18:27:03.180 I/FA      (30576):   adb shell setprop debug.firebase.analytics.app air.com.playcus.bingokingdom
05-04 18:27:03.180 D/FA      (30576): Debug-level message logging enabled
05-04 18:27:03.193 V/FA      (30576): Persisting first open: 1525447623027
05-04 18:27:03.256 E/FA      (30576): AppMeasurementService not registered/enabled
05-04 18:27:03.257 E/FA      (30576): Uploading is not possible. App measurement disabled
05-04 18:27:03.626 V/FA      (30576): Checking service availability
05-04 18:27:03.692 V/FA      (30576): Service available
05-04 18:27:03.692 V/FA      (30576): Setting useService: true
05-04 18:27:03.695 V/FA      (30576): Connecting to remote service
05-04 18:27:03.735 V/FA      (30576): Activity resumed, time: 26951185
05-04 18:27:03.742 I/FA      (30576): Tag Manager is not found and thus will not be used
05-04 18:27:06.670 D/FA      (30576): Connected to remote service
05-04 18:27:06.670 V/FA      (30576): Processing queued up service tasks: 1
05-04 18:27:09.827 V/FA      (31298): Cancelling job. JobID: 3059249

So
05-04 18:27:03.256 E/FA      (30576): AppMeasurementService not registered/enabled
05-04 18:27:03.257 E/FA      (30576): Uploading is not possible. App measurement disabled

Any another application starts AppMeasurementService normally (another ane - too).

- AIR SDK version: 29.0.0.122
- Device OS: Android 7.0 (tested on another versions - did not works too)
- Device version: Samsung Galaxy A7 2017 Duos SM-A720F
- Development IDE: IntelliJ Idea 2018.1
- Development OS: Windows10

P.S. In another ane - Firebase SDK 12.0.1

**Comment by marchbold** [comment]
Hi,

Can you post your manifest additions? The AppMeasurementService should be one of the additions in there:

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions#android-manifest-additions

Regarding versions, we are currently updating to version 15.

**Comment by ikuprin** [comment]
Hi.
Here is it.
[android.txt](https://github.com/distriqt/ANE-Firebase/files/1976559/android.txt)

**Comment by marchbold** [comment]
Looks as though you have the correct AppMeasurementReceiver and AppMeasurementService nodes.

What version of the ANEs are you using? Have you updated all the dependent ANEs as well?

**Comment by ikuprin** [comment]
I'm using latest version of all distriqt anes - all was downloaded at Friday.
I'm using clean project - just created in Idea. There is no any other code or anes or smth else in the project. Just 5 anes for firebase and this little part of code:

var success:Boolean = Firebase.service.initialiseApp();
trace(success); //true
var event:EventObject = new EventObject();
event.name = EventObject.APP_OPEN;
Firebase.service.analytics.logEvent( event );

**Comment by ikuprin** [comment]
I can send you full test project with production settings on email. Is it possible?

**Comment by cgascons** [comment]
Hi, I'm also having the exact same issue, please share the results here as soon as it's solved.

**Comment by marchbold** [comment]
@cgascons Can you describe your situation? What ANEs you are using, development environment, logs etc? 

Anything we can use to isolate this issue as we haven't been able to replicate it as yet.

**Comment by marchbold** [comment]
@cgascons Did you enable the debugging outputs for those logs? https://github.com/distriqt/ANE-Firebase/wiki/Core---Analytics#debugging

```
adb shell setprop debug.firebase.analytics.app YOUR_APPLICATION_PACKAGE
```

and

```
adb shell setprop log.tag.FA VERBOSE
```

**Comment by marchbold** [comment]
I can't seem to replicate this issue, but we have a major version update just about ready so hopefully this is fixed with the SDK update. I'll post a beta as soon as we have it ready here.

**Comment by cgascons** [comment]
Ok, will wait for it, 
Thanks

**Comment by Warface** [comment]
I have the same problem... AppMeasurementService is disabled even if it's set to "TRUE" in the xml.

**Comment by Warface** [comment]
Any ETA on this beta release? Thank you

**Comment by marchbold** [comment]
Hi, We are pushing the next release live now as we haven't run into any issues. Let us know if you encounter any problems with the update.

**Comment by gevorg-gsar** [comment]
Is this issue is fixed for anyone? 

We have the same issue with the latest ANE-s.
```
08-31 00:04:00.203	air.com.plexonic.meln2	15038	15321	E	FA      	 AppMeasurementReceiver not registered/enabled
08-31 00:04:00.206	air.com.plexonic.meln2	15038	15321	E	FA      	 AppMeasurementService not registered/enabled
08-31 00:04:00.207	air.com.plexonic.meln2	15038	15321	E	FA      	 Uploading is not possible. App measurement disabled
```

**Comment by marchbold** [comment]
@gevorg-gsar Unfortunately analytics is one of the areas that won't work correctly with manual configuration. This is a known issue with the Firebase SDK and the only solution is to use the configuration files method.

**Comment by david-daal** [comment]
We just tried with AIR SDK 30 and newly generated CustomResources ANE - the problem persists.
Can you please loom into this asap? 
The only thin that was not done according to your instructions for generating ANE was that `ga_trackingId`  ` {YOUR_CLIENT}/services/analytics-service/analytics_property/tracking_id` were missing in our JSON that was downloaded from FireBase. So we left your examples value for that field in `values.xml`. 

Logcat reports the same issue as before.

```
09-02 18:47:01.579	air.com.plexonic.meln2	25632	25672	E	FA      	 AppMeasurementReceiver not registered/enabled
09-02 18:47:01.609	air.com.plexonic.meln2	25632	25672	E	FA      	 AppMeasurementService not registered/enabled
09-02 18:47:01.627	air.com.plexonic.meln2	25632	25672	E	FA      	 Uploading is not possible. App measurement disabled
```

**Comment by marchbold** [comment]
What do you mean by the examples value? You should leave it blank if you aren't migrating from an existing analytics tracking id.

**Comment by david-daal** [comment]
Ok we rebuild the ANE-s  with `ga_trackingId` value empty and the problem persists.
I don't understand how it can work for you. 
@Warface @cgascons does the Firebase Analytics for you on Android now?

**Comment by marchbold** [comment]
Can you enable the debug outputs and post the full log from startup for us?

https://github.com/distriqt/ANE-Firebase/wiki/Core---Analytics#debugging

**Comment by marchbold** [comment]
@david-daal Can you post your manifest additions?

**Comment by david-daal** [comment]
```
        <manifestAdditions>
            <![CDATA[
            <manifest android:installLocation="auto">
                <!--<uses-feature android:glEsVersion="0x00020000" android:required="true" />-->
                <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="27" />
                <supports-screens>
                    android:smallScreens="false"
                    android:normalScreens="true"
                    android:largeScreens="true"
                    android:xlargeScreens="true"
                </supports-screens>
                <!--for Samsung-->
                <uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
                <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>

                <!--for htc-->
                <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>

                <!--for sony-->
                <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>
                <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>

                <!--for apex-->
                <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>

                <!--for solid-->
                <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE"/>

                <!--for huawei-->
                <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE"/>
                <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS"/>

                <!--for ZUK-->
                <uses-permission android:name="android.permission.READ_APP_BADGE"/>

                <!--for OPPO-->
                <uses-permission android:name="com.oppo.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.oppo.launcher.permission.WRITE_SETTINGS"/>

                <!--for EvMe-->
                <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_READ"/>
                <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_WRITE"/>

                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                <uses-permission android:name="android.permission.GET_ACCOUNTS" />
                <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
                <uses-permission android:name="com.android.vending.BILLING" />
                <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
                <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

                <!--NEWLY ADDED-->
                <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
                <uses-permission android:name="android.permission.WAKE_LOCK" />

                <!-- NOT NEEDED YET -->
                <!--<uses-permission android:name="android.permission.READ_PHONE_STATE" />-->


                <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" /> <!-- Required by older versions of Google Play services to create IID tokens -->
                <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
                <permission android:name="air.com.plexonic.meln2.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
                <uses-permission android:name="air.com.plexonic.meln2.permission.C2D_MESSAGE"/>

                 <application android:enabled="true" android:debuggable="false" android:allowBackup="true" android:hardwareAccelerated="false" android:name="android.support.multidex.MultiDexApplication">
                    <receiver android:name="com.infinario.android.infinariosdk.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
                        <intent-filter>
                            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                            <category android:name="com.example.gcm" />
                        </intent-filter>
		            </receiver>
		            <service android:name="com.infinario.android.infinariosdk.GcmIntentService" />

		            <receiver android:name="com.infinario.android.infinariosdk.ReferrerReceiver" android:exported="true" >
                        <intent-filter>
                            <action android:name="com.android.vending.INSTALL_REFERRER" />
                        </intent-filter>
                    </receiver>
                    <activity android:launchMode="singleTop" android:resizeableActivity="false">
                    android:name="com.distriqt.extension.inappbilling.activities.ProductViewActivity"
				    android:theme="@android:style/Theme.Translucent.NoTitleBar">
                        <intent-filter>
						    <action android:name="android.intent.action.MAIN"/>
						    <category android:name="android.intent.category.LAUNCHER"/>
						</intent-filter>
						<intent-filter>
						    <action android:name="android.intent.action.VIEW" />
						    <category android:name="android.intent.category.DEFAULT" />
						    <category android:name="android.intent.category.BROWSABLE" />
						    <data android:scheme="com.plexonic.meln2" />
						</intent-filter>
					</activity>
					<provider
			            android:authorities="air.com.plexonic.meln2.firebaseinitprovider"
                            android:name="com.google.firebase.provider.FirebaseInitProvider"
                            android:exported="false"
                            android:initOrder="100" />
                    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND" >
                        <intent-filter>
                            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                            <category android:name="air.com.plexonic.meln2" />
                        </intent-filter>
                    </receiver>
                    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
                    <receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">
                        <intent-filter>
                             <action android:name="com.android.vending.INSTALL_REFERRER" />
                         </intent-filter>
                    </receiver>
                    <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
                        <intent-filter android:priority="-500">
                            <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
                        </intent-filter>
                    </service>
                    <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
                        <meta-data
                            android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
                            android:value="com.google.firebase.components.ComponentRegistrar" />
                        <meta-data
                            android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                            android:value="com.google.firebase.components.ComponentRegistrar" />
                        <meta-data
                            android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                            android:value="com.google.firebase.components.ComponentRegistrar" />
                    </service>

                    <activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
                    <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="Pet Savers" />
                    <activity android:name="com.facebook.CustomTabMainActivity" />
                    <activity android:name="com.facebook.CustomTabActivity" android:exported="true" >
                        <intent-filter>
                            <action android:name="android.intent.action.VIEW" />
                            <category android:name="android.intent.category.DEFAULT" />
                            <category android:name="android.intent.category.BROWSABLE" />
                            <data android:scheme="fb589551744526445" />
                        </intent-filter>
                    </activity>
                    <activity android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="Login" />
                    <activity
                            android:name="com.google.firebase.auth.internal.FederatedSignInActivity"
                            android:excludeFromRecents="true"
                            android:exported="true"
                            android:launchMode="singleInstance"
                            android:permission="com.google.firebase.auth.api.gms.permission.LAUNCH_FEDERATED_SIGN_IN"
                            android:theme="@android:style/Theme.Translucent.NoTitleBar" />

                    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
					<meta-data android:name="com.facebook.sdk.ApplicationName" android:value="Pet Savers"/>
					<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ 496675130480774"/>

                    <provider android:authorities="com.facebook.app.FacebookContentProvider496675130480774" android:name="com.facebook.FacebookContentProvider" android:exported="true" />
                    <receiver android:name="com.distriqt.extension.notifications.notifications.receivers.NotificationReceiver">
				<intent-filter>
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_SELECTED" />
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_DELETED" />
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_ACTION" />
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_DELAYED" />
					<data android:scheme="dtn" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.BOOT_COMPLETED" />
				</intent-filter>
			</receiver>
			<provider
				android:name="android.support.v4.content.FileProvider"
				android:authorities="APPLICATION_PACKAGE.fileprovider"
				android:grantUriPermissions="true"
				android:exported="false">
				<meta-data
					android:name="android.support.FILE_PROVIDER_PATHS"
					android:resource="@xml/distriqt_notifications_paths" />
			</provider>

			<provider android:name="android.arch.lifecycle.ProcessLifecycleOwnerInitializer" android:authorities="APPLICATION_PACKAGE.lifecycle-trojan" android:multiprocess="true"/>

				</application>
            </manifest>
            ]]>
        </manifestAdditions>
```

**Comment by david-daal** [comment]
@marchbold sorry, issue solved, our mistake!
But we noticed a strange error log from FA in logcat:
```
09-05 01:41:00.331	air.com.plexonic.meln2	20397	20871	E	FA      	 Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference: com.google.android.gms.internal.measurement.zzhl.zza(Unknown Source)
```
Any ideas?

**Comment by marchbold** [comment]
@david-daal Can you tell us what the issue was? 

That error looks like it's internal to the Firebase / Google libraries and should be safe to ignore.

**Comment by gevorg-gsar** [comment]
@marchbold our Android manifest was the reason. We went through your docs and rebuild it from scratch and it fixed the issues.

**Comment by david-daal** [comment]
@marchbold our Android manifest was the reason. We went through your docs and rebuild it from scratch and it fixed the issues.

**Comment by marchbold** [comment]
@david-daal Excellent, glad you found the issue!

**Comment by david-daal** [comment]
We can close this issue btw!
